disabled_rules: # rule identifiers to exclude from running
#  - colon
#  - comma
  - nesting
  - class_delegate_protocol # protocols should be class only to be weakly referenced
#  - control_statement
  - trailing_whitespace  # no trailing whitespace after line
  - void_return # () -> Void
  - cyclomatic_complexity # number of independent paths throught ie function
#  - empty_parentheses_with_trailing_closure
  - unused_optional_binding
excluded: # paths to ignore during linting. Takes precedence over `included`.
#  - Carthage
  - Pods
#  - LetSwiftUITests
  - LetSwiftTests
# - Source/ExcludedFolder
# - Source/ExcludedFile.swift
# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
trailing_whitespace:
  warning: 2
line_length: 1000
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 400 # error
# or they can set both explicitly
file_length:
  warning: 300
  error: 500
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 3 # only warning
  excluded: iPhone # excluded via string
function_parameter_count:
  warning: 5
  error: 6
identifier_name:
  min_length: 2
  max_length:
    warning: 50
cyclomatic_complexity:
  warning: 6
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle)
